In [1]:
import torch

checkpoint_path = r'D:\workspace\python_ws\pose-master\checkpoints\error_checkpoint_1495.pth'
checkpoint = torch.load(checkpoint_path)


In [2]:
checkpoint.keys()

dict_keys(['model_state_dict', 'inputs', 'labels', 'epoch'])

In [3]:
checkpoint['model_state_dict'].keys()

odict_keys(['features.0.weight', 'features.0.bias', 'features.2.weight', 'features.2.bias', 'features.5.weight', 'features.5.bias', 'features.7.weight', 'features.7.bias', 'features.10.weight', 'features.10.bias', 'features.12.weight', 'features.12.bias', 'features.14.weight', 'features.14.bias', 'features.17.weight', 'features.17.bias', 'features.19.weight', 'features.19.bias', 'features.21.weight', 'features.21.bias', 'features.24.weight', 'features.24.bias', 'features.26.weight', 'features.26.bias', 'features.28.weight', 'features.28.bias', 'classifier.0.weight', 'classifier.0.bias', 'classifier.3.weight', 'classifier.3.bias', 'classifier.6.weight', 'classifier.6.bias'])

In [4]:
image_tensor = checkpoint['inputs'][0]


In [5]:
import cv2
import numpy as np
for image_tensor in checkpoint['inputs']:
    # 将张量从GPU移动到CPU（如果在GPU上）
    image_tensor_cpu = image_tensor.cpu()

    # 将PyTorch张量转换为NumPy数组
    image_array = image_tensor_cpu.numpy()

    # 将NumPy数组转换为OpenCV格式的图像（灰度或彩色）
    if image_array.shape[0] == 1:
        image_array = image_array.squeeze()  # 移除单通道的维度
        image = cv2.cvtColor(image_array, cv2.COLOR_GRAY2BGR)  # 转为彩色图像
    else:
        image = cv2.cvtColor(image_array.transpose(1, 2, 0), cv2.COLOR_RGB2BGR)  # 转换通道顺序

    # 显示图像
    cv2.imshow('Image', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


In [45]:
torch.set_printoptions(profile="full")
print(image_tensor)

tensor([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
           0.,  0.,  0.,  0.,  0.,  0., 

In [14]:
cv2.imshow('img',image_tensor.cpu().numpy())
cv2.waitKey(0)
cv2.destroyAllWindows

<function destroyAllWindows>

In [7]:
import cv2
from load_dataset import SkeletonDataset
dataset = SkeletonDataset(r'dataset\train')



In [3]:
img1 = dataset.__getitem__(0)['image']
img2 = dataset._transform_data(dataset.__getitem__(0))['image']

lab1 = dataset.__getitem__(0)['skeleton']
lab2 = dataset._transform_data(dataset.__getitem__(0))['skeleton']


In [4]:
img1,img2,

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 tensor([[[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]]], dtype=torch.uint8))

In [5]:
lab1,lab2

(array([[ 0.76540871,  1.41373381,  0.08107126],
        [ 0.83256944,  1.33402201,  0.06845932],
        [ 0.70894775,  1.32755159,  0.06942557],
        [ 0.75724945,  1.51040095,  0.06722771],
        [ 0.80219851,  1.1012323 ,  0.23998243],
        [ 0.53757395,  1.12154069,  0.19344228],
        [ 0.75562346,  1.6415886 ,  0.07443786],
        [ 0.68554598,  0.92873197,  0.02731857],
        [ 0.52087232,  0.8798047 ,  0.02427817],
        [ 0.75649626,  1.68812956,  0.10848998],
        [ 0.67843025,  0.82642024,  0.06893958],
        [ 0.44822234,  0.81803202,  0.07913519],
        [ 0.7465715 ,  1.86872529,  0.07374465],
        [ 0.82396932,  1.79909295,  0.08260155],
        [ 0.67809889,  1.78923344,  0.07730278],
        [ 0.74361452,  1.92078206,  0.12297228],
        [ 0.91184138,  1.80437392,  0.07117691],
        [ 0.58754209,  1.77520671,  0.06377431],
        [ 1.04239259,  1.64878177, -0.0020691 ],
        [ 0.51524533,  1.58517394,  0.03471896],
        [ 1.18201068

In [8]:
cv2.imshow('img1',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
cv2.imshow('img2',img2.numpy().squeeze())
cv2.waitKey(0)
cv2.destroyAllWindows()