In [7]:
import torch

# 假设你有gender和x张量
gender = torch.randint(0,2,(8,1))  # 0表示女性，1表示男性
x = torch.rand(8, 3)  # 3个样本，每个样本有85个特征
print(gender)
print(x)
# 创建男性和女性的掩码
mask_female = gender == 0  # 创建女性的掩码
mask_male = gender == 1  # 创建男性的掩码
print(mask_female)
print(mask_male)
# 使用掩码分离x中的数据
x_f = x[mask_female.squeeze()]
x_m = x[mask_male.squeeze()]

# 打印分离后的张量
print("Female Data (x_f):")
print(x_f)
print("Male Data (x_m):")
print(x_m)


tensor([[0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1]])
tensor([[0.0814, 0.7664, 0.4777],
        [0.7717, 0.1156, 0.3411],
        [0.0318, 0.1302, 0.7603],
        [0.0435, 0.2263, 0.5243],
        [0.2197, 0.6377, 0.0478],
        [0.7172, 0.7981, 0.2025],
        [0.0900, 0.4057, 0.2957],
        [0.2947, 0.5221, 0.4062]])
tensor([[ True],
        [False],
        [ True],
        [False],
        [False],
        [ True],
        [ True],
        [False]])
tensor([[False],
        [ True],
        [False],
        [ True],
        [ True],
        [False],
        [False],
        [ True]])
Female Data (x_f):
tensor([[0.0814, 0.7664, 0.4777],
        [0.0318, 0.1302, 0.7603],
        [0.7172, 0.7981, 0.2025],
        [0.0900, 0.4057, 0.2957]])
Male Data (x_m):
tensor([[0.7717, 0.1156, 0.3411],
        [0.0435, 0.2263, 0.5243],
        [0.2197, 0.6377, 0.0478],
        [0.2947, 0.5221, 0.4062]])


In [1]:
import torch

# 假设你有gender和x_f、x_m张量
gender = torch.tensor([[0], [1], [0]])  # 0表示女性，1表示男性
x_f = torch.rand(2, 85)  # 女性数据
x_m = torch.rand(1, 85)  # 男性数据

# 创建原始的x张量
x_original = torch.empty(gender.size(0), 85)  # 创建一个与gender相同大小的空张量

# 根据gender的取值将x_f和x_m放回原始x张量中
x_original[gender == 0] = x_f
x_original[gender == 1] = x_m

# 打印原始的x张量
print("Original Data (x_original):")
print(x_original)


IndexError: The shape of the mask [3, 1] at index 1 does not match the shape of the indexed tensor [3, 85] at index 1