In [7]:
import torch

# 假设你有gender和x张量
gender = torch.randint(0,2,(8,1))  # 0表示女性，1表示男性
x = torch.rand(8, 3)  # 3个样本，每个样本有85个特征
print(gender)
print(x)
# 创建男性和女性的掩码
mask_female = gender == 0  # 创建女性的掩码
mask_male = gender == 1  # 创建男性的掩码
print(mask_female)
print(mask_male)
# 使用掩码分离x中的数据
x_f = x[mask_female.squeeze()]
x_m = x[mask_male.squeeze()]

# 打印分离后的张量
print("Female Data (x_f):")
print(x_f)
print("Male Data (x_m):")
print(x_m)


tensor([[0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1]])
tensor([[0.0814, 0.7664, 0.4777],
        [0.7717, 0.1156, 0.3411],
        [0.0318, 0.1302, 0.7603],
        [0.0435, 0.2263, 0.5243],
        [0.2197, 0.6377, 0.0478],
        [0.7172, 0.7981, 0.2025],
        [0.0900, 0.4057, 0.2957],
        [0.2947, 0.5221, 0.4062]])
tensor([[ True],
        [False],
        [ True],
        [False],
        [False],
        [ True],
        [ True],
        [False]])
tensor([[False],
        [ True],
        [False],
        [ True],
        [ True],
        [False],
        [False],
        [ True]])
Female Data (x_f):
tensor([[0.0814, 0.7664, 0.4777],
        [0.0318, 0.1302, 0.7603],
        [0.7172, 0.7981, 0.2025],
        [0.0900, 0.4057, 0.2957]])
Male Data (x_m):
tensor([[0.7717, 0.1156, 0.3411],
        [0.0435, 0.2263, 0.5243],
        [0.2197, 0.6377, 0.0478],
        [0.2947, 0.5221, 0.4062]])


In [8]:
import torch

# 假设你有gender和x张量
batch_size = 8  # 批量大小
x_dim = 3  # x张量的维度
gender = torch.randint(2, (batch_size, 1))  # 随机生成0和1表示性别
x = torch.rand(batch_size, x_dim)  # 随机生成x张量
print(gender)
print(x)
# 将gender扩展到与x的维度相匹配
gender_expanded = gender.expand(-1, x_dim)

# 根据gender_expanded将x分成x_f和x_m
x_f = x * (gender_expanded == 0).float()
x_m = x * (gender_expanded == 1).float()

# 处理x_f和x_m（这里示意性地进行了加法和减法操作）
x_f_processed = x_f + 1  # 做一些处理，这里示意性地加1
x_m_processed = x_m - 1  # 做一些处理，这里示意性地减1

# 创建一个新的x张量，将x_f_processed和x_m_processed相加
x_new = x_f_processed + x_m_processed

# 打印处理后的x张量
print("Processed Data (x_new):")
print(x_new)


tensor([[1],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1]])
tensor([[0.0344, 0.9682, 0.9495],
        [0.6232, 0.3157, 0.1482],
        [0.2002, 0.1071, 0.9877],
        [0.1200, 0.0824, 0.8861],
        [0.1047, 0.2425, 0.6717],
        [0.5006, 0.6922, 0.0376],
        [0.3531, 0.3554, 0.2925],
        [0.4474, 0.7488, 0.7145]])
Processed Data (x_new):
tensor([[0.0344, 0.9682, 0.9495],
        [0.6232, 0.3157, 0.1482],
        [0.2002, 0.1071, 0.9877],
        [0.1200, 0.0824, 0.8861],
        [0.1047, 0.2425, 0.6717],
        [0.5006, 0.6922, 0.0376],
        [0.3531, 0.3554, 0.2925],
        [0.4474, 0.7488, 0.7145]])


In [28]:
import torch

# 假设你有gender和x张量
gender = torch.tensor([[0], [1], [0], [1], [1], [0], [0], [1]])  # 0表示女性，1表示男性
x = torch.rand(8, 3)  # 输入数据 x，形状为 (batch_size, 85)
print(gender,x)

# 根据gender的取值将x分成x_f和x_m
x_f = x[gender.squeeze() == 0]  # 选择gender为0的行作为女性数据
x_m = x[gender.squeeze() == 1]  # 选择gender为1的行作为男性数据

# 分别对x_f和x_m进行处理
x_f = x_f.unsqueeze(-1)
x_m = x_m.unsqueeze(-1)

print(x_f.shape,x_m.shape)
# 重新排列x_f和x_m以匹配原始顺序
processed_x = torch.empty(x.unsqueeze(-1).size())  # 创建与x相同大小的空张量
processed_x[gender.squeeze() == 0] = x_f  # 将x_f数据放回原始位置
processed_x[gender.squeeze() == 1] = x_m  # 将x_m数据放回原始位置

mesh_f = torch.randn(4, 6000, 3)
joints_f = torch.randn(4, 72)

mesh_m = torch.randn(4, 6000, 3)
joints_m = torch.randn(4, 72)

processed_mesh = torch.empty((8, 6000, 3))  # 创建与x相同大小的空张量
processed_mesh[gender.squeeze() == 0] = mesh_f  # 将x_f数据放回原始位置
processed_mesh[gender.squeeze() == 1] = mesh_m  # 将x_m数据放回原始位置

processed_joints = torch.empty((8, 72))  # 创建与x相同大小的空张量
processed_joints[gender.squeeze() == 0] = joints_f  # 将x_f数据放回原始位置
processed_joints[gender.squeeze() == 1] = joints_m  # 将x_m数据放回原始位置



# 打印处理后的数据
print("Processed Data (processed_x):")
print(processed_x)


tensor([[0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1]]) tensor([[0.1271, 0.6531, 0.5591],
        [0.8654, 0.5473, 0.9488],
        [0.3214, 0.9176, 0.1691],
        [0.4032, 0.6906, 0.0270],
        [0.7516, 0.9127, 0.2870],
        [0.3203, 0.7415, 0.2878],
        [0.5738, 0.1233, 0.2634],
        [0.8032, 0.1916, 0.5088]])
torch.Size([4, 3, 1]) torch.Size([4, 3, 1])
Processed Data (processed_x):
tensor([[[0.1271],
         [0.6531],
         [0.5591]],

        [[0.8654],
         [0.5473],
         [0.9488]],

        [[0.3214],
         [0.9176],
         [0.1691]],

        [[0.4032],
         [0.6906],
         [0.0270]],

        [[0.7516],
         [0.9127],
         [0.2870]],

        [[0.3203],
         [0.7415],
         [0.2878]],

        [[0.5738],
         [0.1233],
         [0.2634]],

        [[0.8032],
         [0.1916],
         [0.5088]]])


In [38]:
mesh_f[2],processed_mesh[5]

(tensor([[ 2.0568,  1.1959, -0.2532],
         [ 0.2371,  0.5673, -1.3237],
         [ 0.8781,  0.8575, -0.1877],
         ...,
         [ 1.0263,  2.4927, -0.3614],
         [-0.0810, -1.1632, -0.7085],
         [-0.4976, -1.5743, -1.8232]]),
 tensor([[ 2.0568,  1.1959, -0.2532],
         [ 0.2371,  0.5673, -1.3237],
         [ 0.8781,  0.8575, -0.1877],
         ...,
         [ 1.0263,  2.4927, -0.3614],
         [-0.0810, -1.1632, -0.7085],
         [-0.4976, -1.5743, -1.8232]]))

In [40]:
mesh_m[2],processed_mesh[4]

(tensor([[-0.1984, -0.1537, -0.1504],
         [-0.3996, -0.4935, -0.6408],
         [-0.8010,  0.3093, -0.3793],
         ...,
         [ 0.7251, -0.4246, -0.3149],
         [ 0.3694,  0.1718, -0.6035],
         [-1.5826,  0.7855,  0.1098]]),
 tensor([[-0.1984, -0.1537, -0.1504],
         [-0.3996, -0.4935, -0.6408],
         [-0.8010,  0.3093, -0.3793],
         ...,
         [ 0.7251, -0.4246, -0.3149],
         [ 0.3694,  0.1718, -0.6035],
         [-1.5826,  0.7855,  0.1098]]))

In [41]:
joints_f[0],processed_joints[0]

(tensor([-5.4112e-01, -6.7420e-01,  3.8781e-01,  5.6288e-01,  6.2125e-01,
          9.4689e-01, -7.1419e-01, -4.6756e-01,  1.0537e+00, -4.5413e-02,
         -2.0340e+00,  3.1156e-01, -2.5357e-01, -1.4817e+00, -1.6746e-01,
         -1.4350e+00,  4.1970e-01, -4.8334e-01, -1.1696e+00, -6.5862e-01,
          8.1335e-01, -1.0937e-01, -1.3892e+00, -5.6531e-01,  4.5582e-01,
          1.4296e+00,  7.7453e-02,  2.1371e+00,  1.3271e+00,  7.4384e-01,
         -4.9746e-01, -2.3690e+00, -1.7474e+00,  7.7738e-01,  3.8492e-01,
         -1.1240e-01,  7.2116e-01, -1.3833e+00, -5.1643e-01,  2.1659e+00,
          1.5182e+00, -7.0928e-01,  9.0592e-02, -1.1309e-03, -2.9468e-01,
          6.2205e-01,  4.5330e-02,  1.6739e+00,  1.3498e-01,  7.8602e-03,
          1.5684e+00, -2.6570e+00,  3.9665e-01,  2.0873e-01,  3.1909e-01,
         -3.5836e-01, -3.2203e-01,  5.2514e-01, -2.8596e-01,  5.2141e-01,
          2.8138e-01,  9.6294e-01, -1.0071e-01, -1.3914e+00,  2.4342e+00,
          3.0020e-02,  1.3779e-01, -1.

In [20]:
import torch

def gender_split_process(x,gender):
    '''
    x: 输入的待处理的tensor
    gender: tensor中元素对应的gender
    '''
    # 根据gender的取值将x分成x_f和x_m
    x_f = x[gender.squeeze() == 0]  # 选择gender为0的行作为女性数据
    x_m = x[gender.squeeze() == 1]  # 选择gender为1的行作为男性数据

    # 分别对x_f和x_m进行处理
    # 这里可以添加任何你需要的处理操作
    x_f = x_f.unsqueeze(0)
    x_m = x_m.unsqueeze(-1)


    # 重新排列x_f和x_m以匹配原始顺序
    processed_x = torch.empty(x.size())  # 创建与x相同大小的空张量
    processed_x[gender.squeeze() == 0] = x_f  # 将x_f数据放回原始位置
    processed_x[gender.squeeze() == 1] = x_m  # 将x_m数据放回原始位置

    # 打印处理后的数据
    print("Processed Data (processed_x):")
    print(processed_x)


In [17]:
# 假设你有gender和x张量
gender = torch.tensor([[0], [1], [0], [1], [1], [0], [0], [1]])  # 0表示女性，1表示男性
x = torch.rand(8, 3)  # 输入数据 x，形状为 (batch_size, 85)


In [21]:
gender_split_process(x,gender)
gender

RuntimeError: shape mismatch: value tensor of shape [4, 3, 1] cannot be broadcast to indexing result of shape [4, 3]